language: node_js

env:
  - CXX=g++-4.8 TEST_DIR='app/UMS'

node_js:
  - "6"

services: mongodb

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: false

before_install:
  - $CXX --version
  - if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;

install: true

script: cd $TEST_DIR && npm install && npm run cover
after_success: 'npm run coveralls'